### ISSUE TITLE
Compatibility with Gradle 8

### ISSUE THREAD

**Issue by bddckr** [gmazzo/android-jacoco-aggregated-demo#1]
Hi! Thanks a lot for this demo project (and the blog post)!

I'm trying to update this demo project to work with the latest versions of the various dependencies. While the latest Android Gradle Plugin version has deprecated a few things that the coverage plugin uses (something I'm looking at later), a real blocking issue is encountered once you update Gradle to 8.0 (run `./gradlew wrapper --gradle-version=8.0`): The configuration `allCodeCoverageReportClassDirectories` no longer exists.

gradle/gradle#22616 seems to have the change in it.

I believe (configurations and variants are pretty new to me still!) what we need to do is to use [JacocoReportAggregationPlugin](https://github.com/gradle/gradle/blob/0ff0f8a55f7a3665f9463a6eb173c50d8bb727d6/subprojects/jacoco/src/main/java/org/gradle/testing/jacoco/plugins/JacocoReportAggregationPlugin.java)'s `aggregateCodeCoverageReportResults` instead of `allCodeCoverageReportClassDirectories`.

However, once I do that, it looks like the variant matching fails to select our `codeCoverageElements` because `aggregateCodeCoverageReportResults` no longer is a configuration specific for source directories and instead uses `artifactView`s for the various attribute-based matching of data (sources + classes + execution data). We can no longer simply add our own attribute to change what gets selected as there doesn't seem to be any way to adjust how those artifact views are configured. There's no API to "get that artifact view to add an attribute to it".

tl;dr: Updating the version catalog to the following **and updating Gradle to 8.0** requires changes to the coverage plugin. Any idea what those are?
```toml
[versions]
agp = "7.4.1"
androidx-lifecycle = "2.5.1"
androidx-navigation = "2.5.3"
kotlin = "1.8.10"

[libraries]
androidx-annotation = "androidx.annotation:annotation:1.5.0"
androidx-appcompat = "androidx.appcompat:appcompat:1.6.1"
androidx-constraintlayout = "androidx.constraintlayout:constraintlayout:2.1.4"
androidx-core = "androidx.core:core-ktx:1.9.0"
androidx-livedata = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "androidx-lifecycle" }
androidx-navigation-fragment = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "androidx-navigation" }
androidx-navigation-ui = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "androidx-navigation" }
androidx-test-espresso = "androidx.test.espresso:espresso-core:3.5.1"
androidx-test-junit = "androidx.test.ext:junit:1.1.5"
androidx-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "androidx-lifecycle" }
google-material = "com.google.android.material:material:1.8.0"
junit = "junit:junit:4.13.2"
robolectric = "org.robolectric:robolectric:4.9.2"

[plugins]
android = { id = "com.android.application", version.ref = "agp" }
android-lib = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
```
